### ISSUE TITLE
gnssFGO/online_fgo/include/graph/GraphBase.h:33:10: fatal error: irt_nav_msgs/msg/residual_sample.hpp: 

### ISSUE THREAD

**Issue by miemiedexiaoyang** [rwth-irt/onlineFGO#4]
/home/jsaon/catkin_ws/src/gnssFGO/online_fgo/include/graph/GraphBase.h:33:10: fatal error: irt_nav_msgs/msg/residual_sample.hpp: 没有那个文件或目录
   33 | #include <irt_nav_msgs/msg/residual_sample.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

I would like to ask what the reason for this is, and I would very much like your answer

**Comment by hz658832** [comment]
Hi Jason,
thanks for the question. 
First of all, are you using ros1 or ros2? Have you checked whether you have cloned the complete repo with submodules? 
I have currently updated the irt_nav_msgs, but the repo `https://github.com/rwth-irt/irt_nav_common.git` should be up-to-date.

Can you check? 
Bests,
Haoming

**Comment by miemiedexiaoyang** [comment]
![Uploading 2024-07-02 20-03-58 的屏幕截图.png…]()

**Comment by miemiedexiaoyang** [comment]
Hello, thank you very much for your reply. I have been trying for a day and it is still the same. My version of ros2 is rolling and all libraries are installed as recommended. Can you help me take a look? The error is in the picture, thank you for your reply, if you can, please contact my email: 1340677979@qq.com. Thank you very much~~~~
![2024-07-02 20-03-58 的屏幕截图](https://github.com/rwth-irt/gnssFGO/assets/111719284/5a3b56de-7cfb-42ec-b954-b720e2eb2630)

**Comment by miemiedexiaoyang** [comment]
I checked that all the git folders are there.

**Comment by miemiedexiaoyang** [comment]
This problem has troubled me for many days

**Comment by hz658832** [comment]
Hi, sure, I am closing this issue and coming back to you using mail.
